Vagrant.configure("2") do |config|
  config.vm.box = "r3ap3rpy/debian9.8.0"
  config.vm.hostname = "hellodebian"

  config.vm.network "public_network" 

  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 1024
  end

end
