Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "hellocento"

  config.vm.network "public_network", bridge: "Internet"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.synced_folder "F:\\", "/fdrive",
  {
    disabled: false,
    type: "smb",
    mount_options: ["vers=3.0"],
    smb_username: ENV['SMB_USER'],
    smb_password: ENV['SMB_PASS'],
  }

  config.vm.provider "hyperv" do |hyperv|
    hyperv.cpus = 2
    hyperv.memory = 1024
    hyperv.vmname = "hellocento"
    hyperv.enable_virtualization_extensions = true
    hyperv.linked_clone = true
  end


  config.vm.provision "shell", path: "arged.sh", args: ['testfolder','testfile']


end
