
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "hellocento"

  config.vm.network "public_network", bridge: "Internet"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.synced_folder "F:\\", "/fdrive",
  {
    disabled: false,
    type: "smb",
    mount_options: ["vers=3.0"],
    smb_username: ENV['SMB_USER'],
    smb_password: ENV['SMB_PASS'],
  }

  config.vm.provider "hyperv" do |hyperv|
    hyperv.cpus = 2
    hyperv.memory = 1024
    hyperv.vmname = "hellocento"
    hyperv.enable_virtualization_extensions = true
    hyperv.linked_clone = true
  end

  config.vm.provision "shell", inline: <<-SHELL
  useradd -m -p '$6$AcOyr0G7bp0w72KD$lxsN/PekbvP4QpfUtSeEemon4fmf49zyYj5X0ITf0NTB67t9AvjIJ54i1AhQ8srq.wUGI34qIdJtSmGXZff4E/' -s /bin/bash r3ap3rpy
  usermod -a -G wheel r3ap3rpy 
  mkdir -p /home/r3ap3rpy/.ssh
  cp /fdrive/DevOps/Vagrant/ssh_keys/r3ap3rpy/* /home/r3ap3rpy/.ssh/
  cat /home/r3ap3rpy/.ssh/ds_id_rsa.pub > /home/r3ap3rpy/.ssh/authorized_keys
  chown r3ap3rpy.r3ap3rpy -R /home/r3ap3rpy/.ssh
  chmod 400 /home/r3ap3rpy/.ssh/id_rsa

  SHELL

  #config.vm.provision "shell", path: "bootstrap.sh"


end
