Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "C:\\users\\r3ap3rpy\\Documents\\", "/fdrive",
    { 
      disabled: false, 
      type: "smb",
      mount_options:['vers=3.0'],
      smb_username: ENV['SMB_USER'],
      smb_password: ENV['SMB_PASS'] 
    }

  config.vm.provision "shell", path: "configure_ssh.sh"
  config.vm.provision "shell", path: "add_user.sh", args: ['ansible']
  config.vm.provision "shell", path: "add_keys.sh"


  config.vm.define "ansiblemaster" do |master|    
    master.vm.box = "centos/7"
    master.vm.hostname = "AMaster"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.name = "AMaster"
    end
    master.vm.provision "last", type: "shell", path: "prepare_master.sh"
    master.vm.provision "install_mitogen.sh", type: "shell", path: "install_mitogen.sh"
    master.vm.provision "set_ansible_permissions.sh", type: "shell", path: "set_ansible_permissions.sh"
    master.vm.network "public_network", ip: "192.168.0.190"
  end

  config.vm.define "ansibleagenta" do |agent|
    agent.vm.box = "centos/7"
    agent.vm.hostname = "centosA"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "centosA"
      vb.cpus = 1
      vb.memory = 1024
    end    
    agent.vm.network "public_network", ip: "192.168.0.191"
    agent.vm.provision "shell", inline:<<-SHELL
      echo "192.168.0.200 reaperdome" >> /etc/hosts
      echo "192.168.0.201 reaper" >> /etc/hosts
      echo "192.168.0.210 rhel" >> /etc/hosts
    SHELL
  end

  config.vm.define "ansibleagentb" do |agent|
    agent.vm.box = "centos/7"
    agent.vm.hostname = "centosB"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "centosB"
      vb.cpus = 1
      vb.memory = 1024
    end
    agent.vm.network "public_network", ip: "192.168.0.192"
    agent.vm.provision "shell", inline:<<-SHELL
      echo "192.168.0.200 reaperdome" >> /etc/hosts
      echo "192.168.0.201 reaper" >> /etc/hosts
      echo "192.168.0.210 rhel" >> /etc/hosts
    SHELL
  end
  config.trigger.before :destroy do |trigger|
    trigger.run_remote = {inline: "rm -f /fdrive/Vagrant/keys/$(hostname).pub;rm -f /fdrive/Vagrant/keys/$(hostname)"}
    trigger.on_error = :continue
  end
end
